language: minimal
addons:
  ssh_known_hosts: 
    - $server_ip
script: bash scripts/build.sh
branches:
  only:
    - dev
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in ./.travis/deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: dev
