language: minimal
addons:
  ssh_known_hosts: $server_ip
build:
  provider: script
  script: bash scripts/build.sh
  on:
    branch: dev
before_build:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
