version: '3'

services:
  api-db:
    image: postgres
    hostname: postgres
    container_name: 'api-db'
    ports:
      - '5432:5432'
    volumes:
      - pgdata_api:/var/lib/postgresql/data
      - pgconf_api:/etc/postgresql
      - pglog_api:/var/log/postgresql
    env_file:
     - ../.env/api-db.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    container_name: zookeeper
    ports:
        - 2181:2181
        - 2000:2000
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    
  # kafka
  kafka:
      image: confluentinc/cp-kafka:5.5.1
      container_name: kafka
      depends_on:
          - zookeeper
      ports:
          - 9092:9092
      environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # api
  api:
    image: api
    container_name: api
    depends_on:
      - api-db
      - kafka
      - elasticsearch
    ports:
     - '5000:5000'
    env_file:
      - ../.env/api.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - C:\\assets:/knewless/assets

  # PushService
  push:
    image: push
    container_name: push
    depends_on:
      - kafka
    ports:
      - '3003:3003'
    env_file:
      - ../.env/push.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # fileprocessor
  fileprocessor:
    image: fileprocessor
    container_name: fileprocessor
    depends_on:
      - api-db
      - kafka
    ports:
      - '5010:5010'
    volumes:
      - C:\\assets:/knewless/assets
    env_file:
      - ../.env/fileprocessor.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # emailsender
  emailsender:
    image: emailsender
    container_name: emailsender
    depends_on:
      - kafka
    env_file:
      - ../.env/emailsender.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # Frontend
  client:
    image: client
    container_name: client
    depends_on:
      - api
      - push
    ports:
      - '8080:80'
    env_file:
      - ../.env/client.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /data/certs:/etc/nginx/certs
      - C:\\assets:/knewless/assets

#  Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file:
      - ../.env/elastic.env
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata:
    driver: local
  pgdata_api:
    driver: local
  pgconf_api:
    driver: local
  pglog_api:
    driver: local
  shared:
    driver: local
